services:
  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
      args:
        - REACT_APP_GPT=$REACT_APP_GPT
    ports:
      - 8070:8070
    depends_on:
      - model
  model:
    build:
      context: ./ki_model
      dockerfile: Dockerfile
    ports:
      - 8080:8080