@startuml component_diagram
'skinparam linetype ortho

node "Docker Daemon" {
  component "ML-Model Container" as ML {
    portin "8080" as p1
    
    component "Uvicorn-Server" as uvicorn{
    portin " " as p3
    portout " " as p5
    
  }
    node "Linux System" {
        database "Image Directory" as vol
        node "FastAPI" as fastapi
        node "Python Scripts" as python {
            folder "Load and Prediction" as load_and_prediction
            folder "X-AI" as x_ai
        }
    }
  }
  component "                              Web-App Container" as APP {
    portout "8070" as p2
    
    node "NGINX Web-Server" as nginx {
        folder "Public" as public {
            artifact "index.html"
        }
    }
  }
  
  
  
  
}

interface "localhost:8070" as p70

p2 ----right------ p70
p2 -->p1:request
p1 ---> p2: response

p1 <--> p3
p5 <--> fastapi

load_and_prediction ..> vol : Read
vol ..> load_and_prediction : Write



@enduml
